name: Deploy And Build Snap-Spline-Demo Cloud

on:
  push:
    branches:
      - main
      - dev

jobs:
  package-aliyun:
    name: Package and Deploy to Alibaba Cloud
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    env:
      DOCKER_TLS_CERTDIR: "/certs"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      
      - name: Log in to Alibaba Cloud Container Registry
        run: echo ${{ secrets.ALI_REGISTRY_PASSWORD }} | docker login ${{ vars.ALI_REGISTRY }} -u ${{ secrets.ALI_REGISTRY_USER }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ vars.ALI_REGISTRY }}/longan_iot/snap-spline:${{ github.ref_name }} \
            -f ./Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ vars.ALI_REGISTRY }}/longan_iot/snap-spline:${{ github.ref_name }}
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [package-aliyun]
    if: github.ref_name == vars.DEV_BRANCH
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.TEST_SERVER }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_KEY }}
          script: |
            docker login -u ${{ secrets.ALI_REGISTRY_USER }} -p ${{ secrets.ALI_REGISTRY_PASSWORD }} ${{ vars.ALI_REGISTRY }}
            cd /data/workspace/apps && docker-compose pull snap-spline && docker-compose up -d snap-spline
